import type { Metadata } from "next"
import { Urbanist, Figtree, Nunito } from "next/font/google"
import "./globals.css"
import Banner from "./components/layout/Banner"

const urbanist = Urbanist({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  variable: "--font-urbanist",
})

const figtree = Figtree({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700", "800", "900"],
  variable: "--font-figtree",
})

const nunito = Nunito({
  subsets: ["latin"],
  variable: "--font-nunito",
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body
        className={`${urbanist.variable} ${figtree.variable} ${nunito.variable} bg-[var(--background)]`}
      >
        <Banner />
        {children}
      </body>
    </html>
  )
}
