import type { Metadata } from "next"
import { Urbanist, Figtree, Nunito } from "next/font/google"
import "./globals.css"
import Banner from "./components/layout/Banner"
import Header from "./components/layout/Header"

const urbanist = Urbanist({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  variable: "--font-urbanist",
})

const figtree = Figtree({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700", "800", "900"],
  variable: "--font-figtree",
})

const nunito = Nunito({
  subsets: ["latin"],
  variable: "--font-nunito",
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body
        className={`${urbanist.variable} ${figtree.variable} ${nunito.variable} bg-[var(--background)]`}
      >
        <Banner />
        <div className="2xl:w-[1440px] mx-auto xl:relative">
          <div className="px-5 lg:pl-[215px] lg:pr-[211px]">
            <Header />
            {children}
          </div>
        </div>
      </body>
    </html>
  )
}
